### Application
scout.application.name=Scout Warehouse Server
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEynDd0cwaYuYHtRgkn3Sr0py/fKUCAULVBPUFHgXRoz7IijtULCsAnJwM4EdaeV7PnGvQwiBSmBW3S6+/DRw6rw==
