### Application
scout.application.name=Scout Warehouse
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
scout.backendUrl=http://localhost:8080
scout.auth.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCDLb4DgFNu2gCv/NLwTQxciD2FvrN0HhYbDnayPrN5GEA==

### Security
scout.auth.credentials=admin:admin;scott:tiger
scout.auth.credentialsPlaintext=true

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=${user.home}/ch.scout.warehouse-scout.warehouse.ui.html.dev
