### Application
scout.application.name=Scout Warehouse Server
scout.application.version=${project.version}

### Service tunnel
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEThpCBU7bsF/jsKhwG0SYNl+k+X2mZUiikhVueuykbeAjDmETHV3aFRp8Fmg58r6bRzs9K4vr56Ns6Ra3Dm/U/A==
